/* reconboot -- the ReconOS UEFI bootloader.
 *
 * What it does, in order: says hello on whatever console the firmware gave us,
 * finds a framebuffer, opens the volume it was loaded from, reads the kernel
 * off it, places the kernel's segments where the ELF says they go, collects the
 * memory map, leaves UEFI, and jumps.
 *
 * The last two steps are the delicate ones and they are delicate together. See
 * the comment above exit_and_jump().
 */
#include "efi.h"
#include "reconboot.h"
#include "boot_internal.h"

/* Generated by scripts/make-signing-key.sh. Absent in a tree that has never
 * had a key made, and the loader says so at boot rather than pretending. */
#if __has_include("signing_key.h")
#include "signing_key.h"
#endif

/* Where the kernel is, and why the name carries the architecture.
 *
 * The removable-media path UEFI runs without a boot entry is per-architecture
 * already -- BOOTX64.EFI and BOOTAA64.EFI sit side by side in \EFI\BOOT, and a
 * machine runs the one it can. So a single USB stick can carry loaders for both
 * architectures and boot on either, which is exactly what install media should
 * do.
 *
 * The kernel could not. Both loaders opened \reconos\kernel.elf, one filename,
 * so the medium could hold one kernel and the other architecture would read a
 * binary built for a machine it is not. That is not a theoretical objection:
 * the aarch64 loader on such a stick read the x86_64 kernel, was told it wanted
 * to live at 0x100000, and failed there -- which reads as a firmware problem
 * and is a packaging one. (BG-128)
 *
 * The name carries the architecture now. The old path is still tried as a
 * fallback, because media that predates this holds it and there is no reason to
 * refuse to boot from a stick that is merely older than the rule. */
#if defined(__x86_64__)
#define KERNEL_PATH     u"\\reconos\\kernel-x86_64.elf"
#define KERNEL_PATH_STR "\\reconos\\kernel-x86_64.elf"
#else
#define KERNEL_PATH     u"\\reconos\\kernel-aarch64.elf"
#define KERNEL_PATH_STR "\\reconos\\kernel-aarch64.elf"
#endif

#define KERNEL_PATH_OLD u"\\reconos\\kernel.elf"

/* Beside the kernel, and named for it. */
#if defined(__x86_64__)
#define SIGNATURE_PATH u"\\reconos\\kernel-x86_64.elf.sig"
#else
#define SIGNATURE_PATH u"\\reconos\\kernel-aarch64.elf.sig"
#endif

#if defined(__x86_64__)
typedef void (*kernel_entry_fn)(struct reconboot *) __attribute__((sysv_abi));
#else
typedef void (*kernel_entry_fn)(struct reconboot *);
#endif

static EFI_SYSTEM_TABLE  *ST;
EFI_BOOT_SERVICES *BS;
static EFI_HANDLE         IMAGE;

/* --- Console ------------------------------------------------------------
 *
 * UEFI speaks UTF-16. Everything here is ASCII, widened on the way out, because
 * a loader that needs a text encoding library has lost sight of its job. */

void print(const char *s)
{
	CHAR16 buf[128];
	UINTN n = 0;

	while (*s) {
		if (*s == '\n')
			buf[n++] = u'\r';
		buf[n++] = (CHAR16)(unsigned char)*s++;

		if (n >= 120) {
			buf[n] = 0;
			ST->ConOut->OutputString(ST->ConOut, buf);
			n = 0;
		}
	}
	buf[n] = 0;
	ST->ConOut->OutputString(ST->ConOut, buf);
}

void print_hex(UINT64 v)
{
	static const char digits[] = "0123456789abcdef";
	char buf[19];
	int i = 18;

	buf[i] = '\0';
	if (v == 0)
		buf[--i] = '0';
	while (v) {
		buf[--i] = digits[v & 0xf];
		v >>= 4;
	}
	print("0x");
	print(&buf[i]);
}

void print_dec(UINT64 v)
{
	char buf[21];
	int i = 20;

	buf[i] = '\0';
	if (v == 0)
		buf[--i] = '0';
	while (v) {
		buf[--i] = (char)('0' + (v % 10));
		v /= 10;
	}
	print(&buf[i]);
}

/* A failure here cannot be recovered from and must not be silent: the machine
 * is about to look like it hung. Say what went wrong and stop. */
static void fail(const char *what, EFI_STATUS status)
{
	print("\nreconboot: ");
	print(what);
	print(" failed, status ");
	print_hex(status);
	print("\nHalted.\n");

	for (;;)
		BS->Stall(1000000);
}

/* --- Small helpers ------------------------------------------------------ */

static void copy(void *dst, const void *src, UINTN n)
{
	unsigned char *d = dst;
	const unsigned char *s = src;

	while (n--)
		*d++ = *s++;
}

static void zero(void *dst, UINTN n)
{
	unsigned char *d = dst;

	while (n--)
		*d++ = 0;
}

static bool guid_eq(const EFI_GUID *a, const EFI_GUID *b)
{
	const unsigned char *x = (const unsigned char *)a;
	const unsigned char *y = (const unsigned char *)b;

	for (UINTN i = 0; i < sizeof(EFI_GUID); i++)
		if (x[i] != y[i])
			return false;
	return true;
}

/* --- ELF ----------------------------------------------------------------
 *
 * Only what a loader needs: the program headers say which byte ranges of the
 * file belong at which physical addresses. Sections, symbols and relocations
 * are a linker's business and are not read.
 */

#define ELF_MAGIC 0x464C457FU	/* 0x7F 'E' 'L' 'F' */
#define PT_LOAD   1

struct elf64_header {
	uint32_t magic;
	uint8_t  class_, data, version, osabi, abiversion, pad[7];
	uint16_t type, machine;
	uint32_t version2;
	uint64_t entry, phoff, shoff;
	uint32_t flags;
	uint16_t ehsize, phentsize, phnum, shentsize, shnum, shstrndx;
};

struct elf64_phdr {
	uint32_t type, flags;
	uint64_t offset, vaddr, paddr, filesz, memsz, align;
};

/* --- Reading the kernel off the volume we booted from ------------------- */

/* An optional command line, read from a file beside the kernel.
 *
 * The handoff structure has carried a `cmdline` field since checkpoint 4 and
 * the kernel has always honoured it. **This loader never filled it in**, so on
 * every firmware boot the kernel got an empty command line -- and nothing
 * noticed, because every option the kernel takes was being passed by QEMU's
 * `-append`, which only exists on the `-kernel` path that skips this loader
 * entirely.
 *
 * The cost is not obvious until you meet it: an installed system, or an install
 * medium, had no way to tell the kernel anything at all. The installer could
 * not be told which disk to write to; a recovery mode could not be asked for.
 * The protocol supported it and the implementation quietly did not. (BG-131)
 *
 * A file rather than something built in, because the point is that it can be
 * changed on a stick without rebuilding anything. Absent is normal: most boots
 * want nothing said.
 */
/* A device path naming a file on a device.
 *
 * The firmware hands out a path to the *disk*; LoadImage wants a path to the
 * *file*. The second is the first with one more node on the end, and building
 * it by hand is the whole of what a device-path library would do for this case.
 *
 * Every node is length-prefixed and packed with no padding, so the arithmetic
 * is done in bytes and the length field is written a byte at a time -- a 16-bit
 * store to an odd address faults on some machines, which is exactly why the
 * specification defines that field as two bytes rather than one integer.
 */
EFI_DEVICE_PATH_PROTOCOL *file_device_path(const EFI_DEVICE_PATH_PROTOCOL *dev,
					   const CHAR16 *file)
{
	const EFI_DEVICE_PATH_PROTOCOL *n = dev;
	UINTN dev_bytes = 0, name_units = 0, node_bytes, total;
	UINT8 *out;
	EFI_DEVICE_PATH_PROTOCOL *node;
	EFI_STATUS s;
	UINTN i;

	/* How long the device's own path is, up to but not including its
	 * terminator -- which is being replaced rather than kept. */
	while (!dp_is_end(n)) {
		UINT16 l = dp_len(n);

		if (l < 4)
			return 0;		/* a node that cannot be true */
		dev_bytes += l;
		n = (const EFI_DEVICE_PATH_PROTOCOL *)((const UINT8 *)n + l);
	}

	while (file[name_units])
		name_units++;
	name_units++;				/* the terminator is part of it */

	node_bytes = 4 + name_units * sizeof(CHAR16);
	total = dev_bytes + node_bytes + 4;	/* + our own terminator */

	s = BS->AllocatePool(EfiLoaderData, total, (void **)&out);
	if (EFI_ERROR(s))
		return 0;

	for (i = 0; i < dev_bytes; i++)
		out[i] = ((const UINT8 *)dev)[i];

	node = (EFI_DEVICE_PATH_PROTOCOL *)(out + dev_bytes);
	node->Type = MEDIA_DEVICE_PATH;
	node->SubType = MEDIA_FILEPATH_DP;
	dp_set_len(node, (UINT16)node_bytes);

	{
		UINT8 *chars = out + dev_bytes + 4;

		for (i = 0; i < name_units; i++) {
			chars[i * 2] = (UINT8)(file[i] & 0xFF);
			chars[i * 2 + 1] = (UINT8)(file[i] >> 8);
		}
	}

	node = (EFI_DEVICE_PATH_PROTOCOL *)(out + dev_bytes + node_bytes);
	node->Type = END_DEVICE_PATH_TYPE;
	node->SubType = END_ENTIRE_DEVICE_PATH;
	dp_set_len(node, 4);

	return (EFI_DEVICE_PATH_PROTOCOL *)out;
}

static char cmdline_buf[128];

/* Set when the person chose recovery from the menu. It overrides the file on
 * the EFI partition rather than being merged with it: recovery is a decision
 * made in front of the machine, and whatever `\reconos\cmdline` says was
 * decided earlier and elsewhere. */
static BOOLEAN recovery_chosen = FALSE;

static void read_cmdline(EFI_FILE_PROTOCOL *root)
{
	EFI_FILE_PROTOCOL *file;
	EFI_STATUS s;
	UINTN size = sizeof(cmdline_buf) - 1;
	UINTN i;

	cmdline_buf[0] = '\0';

	s = root->Open(root, &file, (CHAR16 *)u"\\reconos\\cmdline",
		       EFI_FILE_MODE_READ, 0);
	if (EFI_ERROR(s))
		return;

	s = file->Read(file, &size, cmdline_buf);
	file->Close(file);

	if (EFI_ERROR(s)) {
		cmdline_buf[0] = '\0';
		return;
	}

	cmdline_buf[size] = '\0';

	/* One line, and no line ending. A file edited on Windows ends CR LF,
	 * and a command line with a carriage return in it matches nothing --
	 * which presents as an option being ignored for no visible reason. */
	for (i = 0; i < size; i++)
		if (cmdline_buf[i] == '\r' || cmdline_buf[i] == '\n') {
			cmdline_buf[i] = '\0';
			break;
		}
}

static BOOLEAN verify_kernel(EFI_FILE_PROTOCOL *root, const void *image,
			     UINTN size);

static void *read_kernel(UINTN *size_out)
{
	EFI_GUID li_guid = EFI_LOADED_IMAGE_PROTOCOL_GUID;
	EFI_GUID fs_guid = EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_GUID;
	EFI_GUID fi_guid = EFI_FILE_INFO_GUID;

	EFI_LOADED_IMAGE_PROTOCOL *li;
	EFI_SIMPLE_FILE_SYSTEM_PROTOCOL *fs;
	EFI_FILE_PROTOCOL *root, *file;
	EFI_STATUS s;

	UINT8 info_buf[512];
	UINTN info_size = sizeof(info_buf);
	UINTN size;
	void *buf;

	/* Which volume did the firmware load *us* from? That is the one the
	 * kernel is on, and asking rather than searching means a machine with
	 * several ReconOS installations boots the one it was told to. */
	s = BS->HandleProtocol(IMAGE, &li_guid, (void **)&li);
	if (EFI_ERROR(s))
		fail("finding our own loaded image", s);

	s = BS->HandleProtocol(li->DeviceHandle, &fs_guid, (void **)&fs);
	if (EFI_ERROR(s))
		fail("opening the filesystem we were loaded from", s);

	s = fs->OpenVolume(fs, &root);
	if (EFI_ERROR(s))
		fail("opening the volume", s);

	read_cmdline(root);

	s = root->Open(root, &file, (CHAR16 *)KERNEL_PATH, EFI_FILE_MODE_READ, 0);
	if (EFI_ERROR(s)) {
		/* Older media, from before the name carried the architecture.
		 * Tried second rather than first so that a stick holding both
		 * gets the right one. */
		s = root->Open(root, &file, (CHAR16 *)KERNEL_PATH_OLD,
			       EFI_FILE_MODE_READ, 0);
	}
	if (EFI_ERROR(s)) {
		print("\nreconboot: could not open " KERNEL_PATH_STR
		      " or \\reconos\\kernel.elf\n");
		fail("opening the kernel", s);
	}

	s = file->GetInfo(file, &fi_guid, &info_size, info_buf);
	if (EFI_ERROR(s))
		fail("asking how large the kernel is", s);

	size = (UINTN)((EFI_FILE_INFO *)info_buf)->FileSize;

	/* EfiLoaderData rather than EfiBootServicesData: this buffer has to
	 * survive ExitBootServices, and boot-services memory does not. */
	s = BS->AllocatePool(EfiLoaderData, size, &buf);
	if (EFI_ERROR(s))
		fail("finding room for the kernel", s);

	UINTN want = size;
	s = file->Read(file, &want, buf);
	if (EFI_ERROR(s))
		fail("reading the kernel", s);
	if (want != size)
		fail("reading the whole kernel", EFI_LOAD_ERROR);

	file->Close(file);

	/* Verified *before* the volume is closed, because the signature is a
	 * second file on it.
	 *
	 * The first version closed the volume two lines above this and then
	 * passed the handle in anyway, under a comment claiming it was still
	 * open. Calling through it landed in freed pool memory, which EDK II
	 * fills with 0xAF -- so the machine stopped with
	 *
	 *     RIP - AFAFAFAFAFAFAFAF
	 *
	 * and the fault looked like a smashed stack in the new arithmetic
	 * rather than a handle used after it was closed. It failed identically
	 * with the verifier compiled out, which is what finally said the crypto
	 * was innocent.
	 *
	 * The comment and the code disagreed and only the machine could tell.
	 * (BG-132) */
	if (!verify_kernel(root, buf, size)) {
		print("reconboot: refusing to start it.\n");

		/* Stopped through the firmware rather than with a halt
		 * instruction: this loader builds for two architectures and
		 * `hlt` exists on one of them. The aarch64 build said so
		 * immediately, which is the right place to find out. Stall
		 * also leaves the machine responsive enough that the message
		 * stays on the screen. */
		for (;;)
			BS->Stall(1000000);
	}

	root->Close(root);
	*size_out = size;

	return buf;
}

/* Places each loadable segment at the physical address the ELF names, and
 * zeroes the part of it that has no bytes in the file -- which is the kernel's
 * BSS, and which the kernel is entitled to find already clear.
 *
 * The pages are claimed from the firmware first. Without that, the kernel would
 * be written into memory UEFI still believes is free, and UEFI is still running
 * at this point. */
static uint64_t load_kernel(void *image, UINTN image_size, uint64_t *entry_out)
{
	struct elf64_header *eh = image;
	uint64_t lowest = ~0ULL, highest = 0;

	if (image_size < sizeof(*eh) || eh->magic != ELF_MAGIC)
		fail("recognising the kernel as an ELF", EFI_LOAD_ERROR);

	for (unsigned i = 0; i < eh->phnum; i++) {
		struct elf64_phdr *ph = (struct elf64_phdr *)
			((uint8_t *)image + eh->phoff + i * eh->phentsize);

		if (ph->type != PT_LOAD || ph->memsz == 0)
			continue;

		if (ph->paddr < lowest)
			lowest = ph->paddr;
		if (ph->paddr + ph->memsz > highest)
			highest = ph->paddr + ph->memsz;
	}

	if (highest == 0)
		fail("finding anything to load in the kernel", EFI_LOAD_ERROR);

	{
		EFI_PHYSICAL_ADDRESS at = lowest & ~0xFFFULL;
		UINTN pages = (UINTN)((highest - at + 0xFFF) / 0x1000);
		EFI_STATUS s = BS->AllocatePages(AllocateAddress, EfiLoaderData,
						 pages, &at);

		/* AllocateAddress can fail because the firmware has something of
		 * its own where the kernel wants to be. That is a real
		 * possibility on a machine we have never seen, and the fix is a
		 * relocatable kernel rather than a retry -- so it is reported
		 * precisely rather than worked around. */
		if (EFI_ERROR(s)) {
			print("\nreconboot: the kernel wants to live at ");
			print_hex(at);
			print(" and the firmware will not give it up.\n");
			fail("claiming the kernel's memory", s);
		}
	}

	for (unsigned i = 0; i < eh->phnum; i++) {
		struct elf64_phdr *ph = (struct elf64_phdr *)
			((uint8_t *)image + eh->phoff + i * eh->phentsize);

		if (ph->type != PT_LOAD || ph->memsz == 0)
			continue;

		copy((void *)(uintptr_t)ph->paddr,
		     (uint8_t *)image + ph->offset, ph->filesz);
		zero((void *)(uintptr_t)(ph->paddr + ph->filesz),
		     ph->memsz - ph->filesz);
	}

	/* Find where to jump. Not the ELF entry point -- that belongs to the
	 * 32-bit trampoline the other boot protocols arrive through. The kernel
	 * carries a header naming its 64-bit entry, and it is found by scanning
	 * the loaded image for the magic. */
	for (uint64_t p = lowest; p + sizeof(struct reconboot_kernel_header) <= highest;
	     p += 8) {
		struct reconboot_kernel_header *h =
			(struct reconboot_kernel_header *)(uintptr_t)p;

		if (h->magic == RECONBOOT_MAGIC && h->version == RECONBOOT_VERSION) {
			*entry_out = h->entry;
			return highest;
		}
	}

	print("\nreconboot: the kernel has no ReconBoot header, so there is\n"
	      "nowhere to jump that is not the 32-bit trampoline.\n");
	fail("finding the kernel's 64-bit entry point", EFI_LOAD_ERROR);
	return 0;
}

/* --- Framebuffer -------------------------------------------------------- */

static void find_framebuffer(struct reconboot_framebuffer *fb)
{
	EFI_GUID gop_guid = EFI_GRAPHICS_OUTPUT_PROTOCOL_GUID;
	EFI_GRAPHICS_OUTPUT_PROTOCOL *gop;
	EFI_STATUS s;

	zero(fb, sizeof(*fb));
	fb->format = RECONBOOT_PIXEL_NONE;

	s = BS->LocateProtocol(&gop_guid, 0, (void **)&gop);
	if (EFI_ERROR(s)) {
		/* A serial-only machine, or one whose firmware offers no
		 * graphics. Not a failure: the kernel has a serial console and
		 * this is exactly what a framebuffer of zero width means. */
		print("  framebuffer  : none offered by this firmware\n");
		return;
	}

	fb->base   = gop->Mode->FrameBufferBase;
	fb->size   = gop->Mode->FrameBufferSize;
	fb->width  = gop->Mode->Info->HorizontalResolution;
	fb->height = gop->Mode->Info->VerticalResolution;

	/* Pitch in bytes, from pixels-per-scanline. The two differ whenever the
	 * firmware pads rows, which is common, and using width here instead is
	 * how a picture ends up sheared. */
	fb->pitch = gop->Mode->Info->PixelsPerScanLine * 4;

	switch (gop->Mode->Info->PixelFormat) {
	case PixelBlueGreenRedReserved8BitPerColor:
		fb->format = RECONBOOT_PIXEL_BGRA;
		break;
	case PixelRedGreenBlueReserved8BitPerColor:
		fb->format = RECONBOOT_PIXEL_RGBA;
		break;
	default:
		/* PixelBitMask and PixelBltOnly. The first needs the masks
		 * interpreting and the second has no linear framebuffer at all.
		 * Reported as unknown rather than guessed at: drawing into a
		 * buffer whose layout we assumed is how you get a display full
		 * of colourful noise. */
		fb->format = RECONBOOT_PIXEL_NONE;
		break;
	}

	print("  framebuffer  : ");
	print_dec(fb->width);
	print("x");
	print_dec(fb->height);
	print(" at ");
	print_hex(fb->base);
	print(", pitch ");
	print_dec(fb->pitch);
	print(fb->format == RECONBOOT_PIXEL_BGRA ? " BGRA\n" :
	      fb->format == RECONBOOT_PIXEL_RGBA ? " RGBA\n" :
	      " layout not understood\n");
}

/* --- Firmware tables ---------------------------------------------------- */

static void find_tables(struct reconboot *bi)
{
	EFI_GUID acpi20 = EFI_ACPI_20_TABLE_GUID;
	EFI_GUID acpi10 = EFI_ACPI_10_TABLE_GUID;
	EFI_GUID dtb    = EFI_DTB_TABLE_GUID;

	for (UINTN i = 0; i < ST->NumberOfTableEntries; i++) {
		EFI_CONFIGURATION_TABLE *t = &ST->ConfigurationTable[i];

		/* ACPI 2.0 wins over 1.0 where both are present, which is why
		 * it is not an else-if: a machine publishing both should be
		 * read through the newer one. */
		if (guid_eq(&t->VendorGuid, &acpi20))
			bi->acpi_rsdp = (uint64_t)(uintptr_t)t->VendorTable;
		else if (guid_eq(&t->VendorGuid, &acpi10) && !bi->acpi_rsdp)
			bi->acpi_rsdp = (uint64_t)(uintptr_t)t->VendorTable;
		else if (guid_eq(&t->VendorGuid, &dtb))
			bi->dtb = (uint64_t)(uintptr_t)t->VendorTable;
	}
}

/* --- Memory map, and leaving --------------------------------------------
 *
 * These are one operation, not two, and the reason is the map key.
 *
 * ExitBootServices only succeeds if the key it is given matches the current
 * state of the memory map. Anything that allocates -- including calling
 * GetMemoryMap itself, which may need a larger buffer -- changes the map and
 * invalidates the key. So the sequence is: allocate generously first, then get
 * the map, then immediately exit with the key it returned, with nothing in
 * between. If the exit fails anyway, the only correct response is to get the
 * map again and retry, because the firmware has changed something underneath.
 *
 * After ExitBootServices returns, none of BS is callable and print() no longer
 * works. Nothing below that line may fail.
 */
static void exit_and_jump(struct reconboot *bi, uint64_t entry)
{
	EFI_MEMORY_DESCRIPTOR *map = 0;
	UINTN map_size = 0, map_key = 0, desc_size = 0;
	UINT32 desc_version = 0;
	EFI_STATUS s;
	struct reconboot_region *regions;

	/* Ask how large the map is, then ask for more than that: getting the
	 * map is itself an allocation, and the map can grow between the two
	 * calls. Four extra descriptors is the conventional slack. */
	s = BS->GetMemoryMap(&map_size, 0, &map_key, &desc_size, &desc_version);
	if (s != EFI_BUFFER_TOO_SMALL)
		fail("asking how large the memory map is", s);

	map_size += desc_size * 8;

	s = BS->AllocatePool(EfiLoaderData, map_size, (void **)&map);
	if (EFI_ERROR(s))
		fail("finding room for the memory map", s);

	/* Room for the translated map, allocated *now*, because allocating it
	 * after the final GetMemoryMap would invalidate the key. */
	s = BS->AllocatePool(EfiLoaderData,
			     (map_size / desc_size) * sizeof(*regions),
			     (void **)&regions);
	if (EFI_ERROR(s))
		fail("finding room for the translated memory map", s);

	bi->regions = (uint64_t)(uintptr_t)regions;

	print("\nreconboot: leaving UEFI.\n");

	for (int attempt = 0; attempt < 4; attempt++) {
		UINTN this_size = map_size;

		s = BS->GetMemoryMap(&this_size, map, &map_key,
				     &desc_size, &desc_version);
		if (EFI_ERROR(s))
			fail("reading the memory map", s);

		/* Translate before exiting. After the exit there is no console
		 * to report a mistake on, so the work is done while there still
		 * is one -- even though it means the map is translated once per
		 * attempt. */
		bi->region_count = 0;
		for (UINTN off = 0; off < this_size; off += desc_size) {
			EFI_MEMORY_DESCRIPTOR *d =
				(EFI_MEMORY_DESCRIPTOR *)((uint8_t *)map + off);
			uint32_t kind;

			switch (d->Type) {
			case EfiConventionalMemory:
			case EfiBootServicesCode:
			case EfiBootServicesData:
				/* Boot services memory becomes ours the instant
				 * we exit, which is the whole point of exiting. */
				kind = RECONBOOT_MEM_USABLE;
				break;
			case EfiLoaderCode:
			case EfiLoaderData:
				/* Ours, and still in use: the kernel image and
				 * this structure are in here. Reclaimable once
				 * the kernel has finished reading it. */
				kind = RECONBOOT_MEM_BOOTLOADER;
				break;
			case EfiACPIReclaimMemory:
				kind = RECONBOOT_MEM_ACPI_RECLAIM;
				break;
			case EfiACPIMemoryNVS:
				kind = RECONBOOT_MEM_ACPI_NVS;
				break;
			case EfiUnusableMemory:
				kind = RECONBOOT_MEM_BAD;
				break;
			default:
				kind = RECONBOOT_MEM_RESERVED;
				break;
			}

			regions[bi->region_count].base = d->PhysicalStart;
			regions[bi->region_count].size = d->NumberOfPages * 0x1000;
			regions[bi->region_count].kind = kind;
			regions[bi->region_count].reserved = 0;
			bi->region_count++;
		}

		s = BS->ExitBootServices(IMAGE, map_key);
		if (!EFI_ERROR(s))
			break;

		/* The map changed underneath us. The key is stale; go round
		 * again. This genuinely happens on real firmware. */
		if (attempt == 3)
			fail("leaving UEFI", s);
	}

	/* No console, no allocator, no firmware services. Just the kernel.
	 *
	 * The cast is not decoration. This loader is compiled for the Microsoft
	 * ABI because that is what UEFI requires, and the kernel is compiled by
	 * gcc for the System V ABI. On x86_64 those disagree about where the
	 * first argument goes -- RCX against RDI -- so calling straight through
	 * would hand the kernel whatever happened to be in RDI. The handoff is
	 * declared System V because the kernel is the thing that has to live
	 * with it afterwards. On aarch64 both ABIs pass the first argument in
	 * x0 and there is nothing to reconcile. */
	/* --- and every register the kernel did not ask for is cleared -------
	 *
	 * A plain call hands over whatever happened to be lying around:
	 * firmware pointers, buffer addresses, and -- because the signature
	 * check runs a few lines above this -- the leftovers of an RSA
	 * verification and a SHA-256. None of it is secret the way a private
	 * key is, and that is not the argument. The argument is that a kernel
	 * which accidentally reads one of them works on the firmware it was
	 * written against and fails on the next, and the failure arrives as a
	 * machine that will not boot with no console to say why.
	 *
	 * Clearing them turns that latent bug into an immediate one, which is
	 * the only kind worth having on a boot path.
	 *
	 * **One register cannot be cleared**, and it is the one holding the
	 * address being jumped to. Naming a target without a register to hold
	 * it is not something either architecture offers here, so it keeps the
	 * kernel's own entry point -- a number the kernel already knows, and
	 * the only leftover this hands over. The kernel checks every other one
	 * and says which it cannot.
	 */
#if defined(__x86_64__)
	{
		register uint64_t arg __asm__("rdi") =
			(uint64_t)(uintptr_t)bi;
		register uint64_t tgt __asm__("rax") = entry;

		/* Nothing is declared clobbered because nothing runs
		 * afterwards: this jump does not return, so the compiler has
		 * no register state to preserve across it. Declaring the
		 * clobbers would be more honest and is not possible -- several
		 * of these are the ones it would use to honour the
		 * declaration. */
		__asm__ volatile(
			"xorl %%ebx, %%ebx\n"
			"xorl %%ecx, %%ecx\n"
			"xorl %%edx, %%edx\n"
			"xorl %%esi, %%esi\n"
			"xorl %%ebp, %%ebp\n"
			"xorl %%r8d, %%r8d\n"
			"xorl %%r9d, %%r9d\n"
			"xorl %%r10d, %%r10d\n"
			"xorl %%r11d, %%r11d\n"
			"xorl %%r12d, %%r12d\n"
			"xorl %%r13d, %%r13d\n"
			"xorl %%r14d, %%r14d\n"
			"xorl %%r15d, %%r15d\n"
			"jmpq *%%rax"
			:
			: "r"(arg), "r"(tgt)
			: "memory");
	}
#elif defined(__aarch64__)
	{
		register uint64_t arg __asm__("x0") =
			(uint64_t)(uintptr_t)bi;

		/* x16 is the intra-procedure-call scratch register, which is
		 * exactly what a jump through a register is meant to use. */
		register uint64_t tgt __asm__("x16") = entry;

		__asm__ volatile(
			"mov x1, #0\n"
			"mov x2, #0\n"
			"mov x3, #0\n"
			"mov x4, #0\n"
			"mov x5, #0\n"
			"mov x6, #0\n"
			"mov x7, #0\n"
			"mov x8, #0\n"
			"mov x9, #0\n"
			"mov x10, #0\n"
			"mov x11, #0\n"
			"mov x12, #0\n"
			"mov x13, #0\n"
			"mov x14, #0\n"
			"mov x15, #0\n"
			"mov x17, #0\n"
			"mov x18, #0\n"
			"mov x19, #0\n"
			"mov x20, #0\n"
			"mov x21, #0\n"
			"mov x22, #0\n"
			"mov x23, #0\n"
			"mov x24, #0\n"
			"mov x25, #0\n"
			"mov x26, #0\n"
			"mov x27, #0\n"
			"mov x28, #0\n"
			"mov x29, #0\n"
			"mov x30, #0\n"
			"br x16"
			:
			: "r"(arg), "r"(tgt)
			: "memory");
	}
#else
	((kernel_entry_fn)(uintptr_t)entry)(bi);
#endif

	/* Not reached. If it is, there is nothing left to report it with. */
	for (;;)
		__asm__ volatile("");
}

/* --- Entry -------------------------------------------------------------- */

static struct reconboot boot_info;

/* --- Verifying the kernel before running it --------------------------------
 *
 * The signature sits beside the kernel as `<name>.sig`: 256 raw bytes, PKCS#1
 * v1.5 over SHA-256, exactly what `openssl dgst -sign` produces. Detached
 * rather than embedded so the kernel stays an ordinary ELF that objdump, gdb
 * and the build system can all still read.
 *
 * **A failure is a refusal to boot**, not a warning and not a countdown. A
 * kernel that fails its signature is either damaged or hostile, and both are
 * reasons to stop. There is no flag to turn this off: a verification with an
 * override is a verification an attacker turns off, and the override that
 * exists "for development" is the one shipped by mistake. Development builds
 * are handled by signing them.
 *
 * What this is worth is bounded and worth saying: it catches a corrupted
 * download, a half-written update, a failing disk, and casual tampering. It is
 * **not** protection against somebody who can write to the EFI System Partition
 * -- they would replace this loader too. That needs the firmware to verify the
 * loader, which is a decision about Secure Boot keys rather than code. See
 * docs/INTEGRITY.md.
 */
static BOOLEAN verify_kernel(EFI_FILE_PROTOCOL *root, const void *image,
			     UINTN size)
{
#ifndef RECONOS_KEY_PRESENT
	(void)root; (void)image; (void)size;

	/* Built without a key. Announced on every boot rather than silent,
	 * because a build that cannot check is a fact somebody should be told
	 * rather than a default they discover later. */
	print("  signature    : not checked (this loader was built without a "
	      "key)\n");
	return TRUE;
#else
	EFI_FILE_PROTOCOL *file;
	EFI_STATUS s;
	UINT8 sig[256];
	UINT8 digest[32];
	UINTN want = sizeof(sig);

	s = root->Open(root, &file, (CHAR16 *)SIGNATURE_PATH,
		       EFI_FILE_MODE_READ, 0);
	if (EFI_ERROR(s)) {
		print("\nreconboot: this kernel is not signed, and this loader "
		      "only runs signed kernels.\n");
		return FALSE;
	}

	s = file->Read(file, &want, sig);
	file->Close(file);

	if (EFI_ERROR(s) || want != sizeof(sig)) {
		print("\nreconboot: the signature file is not 256 bytes.\n");
		return FALSE;
	}

	sha256(image, size, digest);

	if (!rsa2048_verify(reconos_signing_modulus, sig, digest)) {
		print("\nreconboot: this kernel's signature does not match. It "
		      "has been changed since it was built, or it is not "
		      "ours.\n");
		return FALSE;
	}

	print("  signature    : good\n");
	return TRUE;
#endif
}

EFI_STATUS EFIAPI efi_main(EFI_HANDLE image, EFI_SYSTEM_TABLE *system_table)
{
	void *kernel_image;
	UINTN kernel_size;
	uint64_t entry = 0;

	IMAGE = image;
	ST = system_table;
	BS = system_table->BootServices;

	ST->ConOut->ClearScreen(ST->ConOut);
	print("reconboot -- the ReconOS bootloader\n\n");

	zero(&boot_info, sizeof(boot_info));
	boot_info.magic    = RECONBOOT_MAGIC;
	boot_info.version  = RECONBOOT_VERSION;
	boot_info.size     = sizeof(boot_info);
	boot_info.firmware = RECONBOOT_FIRMWARE_UEFI;
	copy(boot_info.loader, "reconboot", 10);

	find_framebuffer(&boot_info.framebuffer);
	find_tables(&boot_info);

	print("  acpi rsdp    : ");
	print_hex(boot_info.acpi_rsdp);
	print("\n  device tree  : ");
	print_hex(boot_info.dtb);
	print("\n");

	/* What else is on this machine. Looked at every boot rather than kept
	 * in a list, because a list has to be maintained as somebody installs
	 * and removes systems, and a stale one offers a choice that does not
	 * work on the one screen where nobody can investigate. */
	{
		EFI_LOADED_IMAGE_PROTOCOL *self;
		EFI_GUID li_guid = EFI_LOADED_IMAGE_PROTOCOL_GUID;
		EFI_HANDLE from = 0;

		/* The medium we were loaded from, so that it is not offered back
		 * to the person as something to boot. */
		if (!EFI_ERROR(BS->HandleProtocol(image, &li_guid,
						  (void **)&self)))
			from = self->DeviceHandle;

		unsigned found = menu_discover(from);

		if (found) {
			int pick;

			menu_print();

			/* Two seconds when recovery is the only extra entry,
			 * five when there are other systems to read.
			 *
			 * Recovery is always offered, so every boot of every
			 * machine now pauses -- and the pause is the price of
			 * the environment being reachable at all. Two seconds
			 * is chosen to be visible without being a tax: long
			 * enough that somebody watching can act, short enough
			 * that a machine restarting at three in the morning is
			 * not kept waiting for a person who is not there. */
			pick = menu_choose(found == 1 && menu_is_recovery(0) ? 2
									    : 5,
					   &boot_info.framebuffer);

			/* If it starts, this does not return. If it declines,
			 * we carry on and start ReconOS -- a machine that ends
			 * up somewhere is better than one that ends up
			 * nowhere. */
			if (pick >= 0) {
				if (menu_is_recovery((unsigned)pick))
					recovery_chosen = TRUE;
				else
					menu_boot((unsigned)pick, image);
			}
		}
	}

	kernel_image = read_kernel(&kernel_size);

	/* After read_kernel, not before: the command line is read from the
	 * volume inside that call, and copying it earlier copied a buffer that
	 * was still empty. Nothing failed -- the kernel simply received no
	 * command line and behaved exactly as it does when there is none. */

	/* And the override goes here for the same reason: read_kernel fills
	 * cmdline_buf, so setting it before that call would be overwritten by
	 * the file, and setting it after the copy below would never reach the
	 * kernel. Between the two is the only correct place, and BG-131 was
	 * exactly this mistake made once already. */
	if (recovery_chosen) {
		/* zero first, then eight bytes. copy() is a fixed-length byte
		 * copy rather than a string copy, so asking it for
		 * sizeof(cmdline_buf) would read 128 bytes out of a 9-byte
		 * literal. */
		zero(cmdline_buf, sizeof(cmdline_buf));
		copy(cmdline_buf, "recovery", 8);
	}

	copy(boot_info.cmdline, cmdline_buf, sizeof(boot_info.cmdline));

	if (cmdline_buf[0]) {
		print("  command line : ");
		print(cmdline_buf);
		print("\n");
	}
	print("  kernel       : ");
	print_dec(kernel_size);
	print(" bytes read\n");

	load_kernel(kernel_image, kernel_size, &entry);
	print("  entry        : ");
	print_hex(entry);
	print("\n");

	exit_and_jump(&boot_info, entry);
	return EFI_LOAD_ERROR;
}
