#!/bin/sh
# Makes a signing key, and emits the modulus as C for the loader to hold.
#
# The public half is **compiled into the bootloader**, not read from the disk
# beside the signature. A key read from the same volume as the thing it verifies
# is not a check at all: anybody who can replace the kernel can replace the key,
# sign their kernel with their own, and the verifier will be delighted.
#
# The private half is a file, and it is the only thing here that matters. This
# script writes it into `keys/` and nothing else refers to it.
#
# Usage: scripts/make-signing-key.sh [keys-dir]
set -eu

DIR=${1:-keys}
ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

command -v openssl >/dev/null 2>&1 || { echo "need openssl" >&2; exit 2; }

mkdir -p "$DIR"

if [ -f "$DIR/reconos-signing.pem" ]; then
	echo "  $DIR/reconos-signing.pem exists; leaving it alone"
else
	# 2048 bits with the usual public exponent, which is what the verifier
	# is written for -- it fixes e at 65537 rather than reading it, because
	# a fixed exponent removes a category of question about what a hostile
	# one could do.
	openssl genrsa -out "$DIR/reconos-signing.pem" 2048 2>/dev/null
	chmod 600 "$DIR/reconos-signing.pem"
	echo "  wrote $DIR/reconos-signing.pem  (the private key -- this is the secret)"
fi

openssl rsa -in "$DIR/reconos-signing.pem" -pubout \
	-out "$DIR/reconos-signing.pub" 2>/dev/null

# The modulus, as 256 raw bytes, turned into a C array. Written to a generated
# header rather than pasted into source, so that changing keys is a build step
# and never an edit somebody makes by hand at two in the morning.
{
	echo "/* Generated by scripts/make-signing-key.sh -- do not edit."
	echo " *"
	echo " * The public modulus of the key the kernel is signed with. Compiled in"
	echo " * rather than read from the medium: a key that travels beside the thing"
	echo " * it verifies is not a check, because whoever replaced the kernel can"
	echo " * replace the key as well."
	echo " */"
	echo "#ifndef RECONBOOT_SIGNING_KEY_H"
	echo "#define RECONBOOT_SIGNING_KEY_H"
	echo
	echo "#define RECONOS_KEY_PRESENT 1"
	echo
	echo "static const UINT8 reconos_signing_modulus[256] = {"
	openssl rsa -in "$DIR/reconos-signing.pem" -noout -modulus |
		sed 's/^Modulus=//' |
		tr -d '\n' |
		sed 's/../0x&, /g' |
		fold -w 72 |
		sed 's/^/\t/'
	echo
	echo "};"
	echo
	echo "#endif /* RECONBOOT_SIGNING_KEY_H */"
} > boot/src/signing_key.h

echo "  wrote boot/src/signing_key.h  (the public modulus, compiled into the loader)"
echo
echo "  Keep $DIR/reconos-signing.pem out of the repository. Losing it means"
echo "  every machine already running a signed kernel needs its loader replaced."
